############################################################ 30__on-window-detect_global.toml

[[on-window-detected]]
if.app-id = 'com.apple.calculator'
run = "layout floating"

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = "layout floating"

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = "move-node-to-workspace 1"

[[on-window-detected]]
if.app-id = 'org.mozilla.firefox'
run = "move-node-to-workspace 2"

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = "move-node-to-workspace 3"

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = "move-node-to-workspace 7"

[[on-window-detected]]
if.app-id = 'net.cozic.joplin-desktop'
run = "move-node-to-workspace 8"
